### ISSUE TITLE
Studio creates conflits

### ISSUE THREAD

**Issue by BenjaminOddou** [nuxt-content/studio#137]
Hello,

When having footnotes, Nuxt Studio automatically adds a header `## Footnotes`. This causes a conflict between the local version (modified by Nuxt Studio) and the remote GitHub version, preventing the user from editing the file in Studio.

Also, it seems that the standard syntax `[^1]: Footnote` is not accepted by Nuxt Studio. Writing markdown directly without Studio would require a more verbose syntax `1. Footnote [↩](#user-content-fnref-1){.data-footnote-backref ariaLabel="Back to reference 1" dataFootnoteBackref=""}` to match Nuxt Studio style.

<img width="629" height="361" alt="Image" src="https://github.com/user-attachments/assets/99eaaeb9-b3db-426a-9b20-d5b3cdd4dd8e" />

**Comment by xue-moe** [comment]
I’ve noticed the same issue. Beyond footnotes, there are additional inconsistencies caused by Nuxt Studio’s automatic transformations:

- **Whitespace and line breaks:** Empty lines or double spaces sometimes get ignored or replaced, causing mismatches between local and remote versions.  
- **Hidden images:**  

```markdown
<img src="https://template.com/banner.png" alt="status" style="display:none;">
```  
gets shortened automatically to:  
```
![status](https://template.com/banner.png){style="display:none;"}
```

- **Tip blocks:**  
```
::tip
---
target: _blank
to: https://template.com
---
::
```  
gets shortened to:  

```markdown
::tip{target="_blank" to="https://template.com"}
```
These automatic changes can lead to conflicts and make editing via Studio more challenging. 

**One suggestion:**

Perhaps Nuxt Studio could allow users to directly edit content based on their GitHub repository as the source, and force commit changes, while clearly informing users of the potential risks. This could help avoid conflicts caused by automatic transformations.

**Comment by BenjaminOddou** [comment]
Perhaps the lint rules behind nuxt studio could be customizable ? I think there is an open source linter project in the pipeline.

![image](https://github.com/user-attachments/assets/35d3a5be-138a-4683-9b1b-07f66e22f7ea)

**Comment by BenjaminOddou** [comment]
https://github.com/nuxt-content/studio/commit/1214cd1a3e1181700fa856f3f72c0e7e1222400b#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R71 👀

**Comment by BenjaminOddou** [comment]
@farnabaz @larbish The issue also affects properties for images and links:

<img width="775" height="273" alt="Image" src="https://github.com/user-attachments/assets/243a28ff-4046-4f3d-ae4b-1825ddc92a85" />


`[link](some-url){target="_blank"}` transformed into `[link](some-url)`

**Comment by larbish** [comment]
@xue-moe  The transformations you see are intentional, we're trying to establish a standardized MDC formatting rules that Nuxt Studio is following. MDC syntax has multiple valid ways to write the same thing which causes the conflicts you've experienced.

We've released [MDCLint](https://github.com/nuxt-content/mdclint) to enforce these standards across all tools. Studio must apply this formatting automatically. Our goal is full parity: run MDCLint on your repo and Studio will maintain that exact format. We need more time (and help) to work on the MDCLint but the idea is that if you find cases where Studio output diverges from MDCLinter this is a bug that can be raised.

**Comment by larbish** [comment]
@BenjaminOddou 

#295 ensures behaviour is good for links:

- `[link](https://external.com/){target="_blank"}` formatted to `[link](https://external.com/)` (external by default)
- `[link](/relative){target="_blank"}` must stays `[link](/relative){target="_blank"}`

#294 might fix several issues with images (including attributes)

**Comment by BenjaminOddou** [comment]
@larbish 
#294 fixed my issue with image attributes! 💚 
However, Markdown links like `[link](https://external.com/)` still don't open in a new window. It looks like the rendered HTML is missing the `target="_blank"` attribute.

<img width="1930" height="212" alt="Image" src="https://github.com/user-attachments/assets/801d6688-1884-4031-9b2e-ba708e433680" />

version tested : `1.2.0`

**Comment by larbish** [comment]
@farnabaz what could be the reason? Could you share a simple repro @BenjaminOddou ? 🤔
